// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bckgndYUV_dout,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_empty_n,
        bckgndYUV_read,
        ovrlayYUV_din,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        ovrlayYUV_full_n,
        ovrlayYUV_write,
        boxHCoord_loc_0,
        boxVCoord_loc_0,
        loopWidth,
        boxColorB,
        conv2_i_i_i129,
        boxColorR,
        and4_i,
        and26_i,
        tobool,
        and10_i,
        patternId_val_load,
        boxSize,
        y,
        motionSpeed,
        vMax,
        hMax,
        zext_ln1889,
        icmp,
        boxColorG,
        crossHairX,
        cmp2_i,
        color,
        boxHCoord_loc_1_out,
        boxHCoord_loc_1_out_ap_vld,
        boxVCoord_loc_1_out,
        boxVCoord_loc_1_out_ap_vld,
        boxHCoord,
        boxHCoord_ap_vld,
        boxVCoord,
        boxVCoord_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] bckgndYUV_dout;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_empty_n;
output   bckgndYUV_read;
output  [23:0] ovrlayYUV_din;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
input   ovrlayYUV_full_n;
output   ovrlayYUV_write;
input  [15:0] boxHCoord_loc_0;
input  [15:0] boxVCoord_loc_0;
input  [15:0] loopWidth;
input  [7:0] boxColorB;
input  [7:0] conv2_i_i_i129;
input  [7:0] boxColorR;
input  [0:0] and4_i;
input  [0:0] and26_i;
input  [0:0] tobool;
input  [0:0] and10_i;
input  [7:0] patternId_val_load;
input  [15:0] boxSize;
input  [15:0] y;
input  [7:0] motionSpeed;
input  [15:0] vMax;
input  [15:0] hMax;
input  [8:0] zext_ln1889;
input  [0:0] icmp;
input  [7:0] boxColorG;
input  [15:0] crossHairX;
input  [0:0] cmp2_i;
input  [7:0] color;
output  [15:0] boxHCoord_loc_1_out;
output   boxHCoord_loc_1_out_ap_vld;
output  [15:0] boxVCoord_loc_1_out;
output   boxVCoord_loc_1_out_ap_vld;
output  [15:0] boxHCoord;
output   boxHCoord_ap_vld;
output  [15:0] boxVCoord;
output   boxVCoord_ap_vld;

reg ap_idle;
reg boxHCoord_loc_1_out_ap_vld;
reg boxVCoord_loc_1_out_ap_vld;
reg boxHCoord_ap_vld;
reg boxVCoord_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln774_reg_911;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln774_fu_436_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] vDir;
reg   [0:0] hDir;
wire   [1:0] whiYuv_2_address0;
wire   [7:0] whiYuv_2_q0;
reg    ovrlayYUV_blk_n;
wire    ap_block_pp0_stage0;
reg    bckgndYUV_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] color_read_reg_786;
wire   [7:0] patternId_val_load_read_reg_833;
wire   [15:0] zext_ln1889_cast_fu_404_p1;
reg   [15:0] zext_ln1889_cast_reg_881;
wire   [15:0] motionSpeed_cast_fu_408_p1;
reg   [15:0] motionSpeed_cast_reg_887;
reg   [15:0] x_1_reg_895;
reg   [15:0] boxVCoord_loc_1_load_reg_901;
reg   [15:0] boxHCoord_loc_1_load_reg_906;
reg   [0:0] icmp_ln774_reg_911_pp0_iter2_reg;
wire   [0:0] trunc_ln774_fu_447_p1;
reg   [0:0] trunc_ln774_reg_915;
wire   [0:0] icmp_ln1884_fu_456_p2;
wire   [0:0] hDir_load_load_fu_462_p1;
wire   [0:0] icmp_ln1889_fu_466_p2;
wire   [0:0] icmp_ln1894_fu_477_p2;
wire   [0:0] vDir_load_load_fu_488_p1;
wire   [0:0] icmp_ln1901_fu_492_p2;
wire   [0:0] icmp_ln1906_fu_503_p2;
wire   [0:0] or_ln1963_fu_577_p2;
reg   [0:0] or_ln1963_reg_948;
reg   [0:0] or_ln1963_reg_948_pp0_iter2_reg;
wire   [1:0] select_ln1975_fu_582_p3;
wire   [7:0] pixIn_fu_595_p1;
wire   [0:0] and_ln1942_fu_679_p2;
wire   [7:0] pixOut_5_fu_689_p3;
reg   [0:0] ap_phi_mux_empty_87_phi_fu_305_p8;
wire   [0:0] ap_phi_reg_pp0_iter1_empty_87_reg_302;
reg   [0:0] ap_phi_mux_empty_86_phi_fu_322_p8;
wire   [0:0] ap_phi_reg_pp0_iter1_empty_86_reg_319;
wire   [1:0] ap_phi_reg_pp0_iter0_phi_ln1975_reg_336;
reg   [1:0] ap_phi_reg_pp0_iter1_phi_ln1975_reg_336;
reg   [1:0] ap_phi_reg_pp0_iter2_phi_ln1975_reg_336;
reg   [7:0] ap_phi_mux_pix_4_phi_fu_350_p12;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_4_reg_347;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_4_reg_347;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_4_reg_347;
reg   [7:0] ap_phi_reg_pp0_iter3_pix_4_reg_347;
reg   [7:0] ap_phi_mux_pix_3_phi_fu_368_p12;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_3_reg_364;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_3_reg_364;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_3_reg_364;
reg   [7:0] ap_phi_reg_pp0_iter3_pix_3_reg_364;
reg   [7:0] ap_phi_mux_pix_phi_fu_388_p12;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_reg_384;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_reg_384;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_reg_384;
reg   [7:0] ap_phi_reg_pp0_iter3_pix_reg_384;
wire   [63:0] zext_ln1975_fu_695_p1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire   [15:0] select_ln1911_fu_524_p3;
wire   [15:0] select_ln1915_fu_548_p3;
reg   [15:0] x_fu_132;
wire   [15:0] x_2_fu_441_p2;
wire    ap_loop_init;
reg   [15:0] boxVCoord_loc_1_fu_136;
reg   [15:0] boxHCoord_loc_1_fu_140;
reg    bckgndYUV_read_local;
wire   [23:0] or_ln808_3_fu_742_p4;
reg    ap_block_pp0_stage0_01001;
reg    ovrlayYUV_write_local;
reg    whiYuv_2_ce0_local;
wire   [15:0] or_ln1884_fu_451_p2;
wire   [15:0] sub_ln1914_fu_514_p2;
wire   [15:0] add_ln1912_fu_519_p2;
wire   [15:0] sub_ln1918_fu_538_p2;
wire   [15:0] add_ln1916_fu_543_p2;
wire   [0:0] icmp_ln1963_fu_572_p2;
wire   [0:0] icmp_ln1932_fu_635_p2;
wire   [15:0] boxBottom_fu_630_p2;
wire   [0:0] icmp_ln1937_fu_651_p2;
wire   [15:0] boxRight_fu_625_p2;
wire   [0:0] icmp_ln1937_1_fu_662_p2;
wire   [0:0] xor_ln1937_fu_656_p2;
wire   [0:0] xor_ln1932_fu_640_p2;
wire   [0:0] icmp_ln1932_1_fu_646_p2;
wire   [0:0] and_ln1942_1_fu_673_p2;
wire   [0:0] and_ln1942_2_fu_667_p2;
wire   [0:0] and_ln1947_fu_685_p2;
wire   [7:0] select_ln1993_fu_707_p3;
wire   [7:0] pixOut_9_fu_700_p3;
wire   [7:0] select_ln1991_fu_728_p3;
wire   [7:0] p_0_2_0_0_0269598_fu_714_p3;
wire   [7:0] empty_fu_735_p3;
wire   [7:0] pixOut_10_fu_721_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_350;
reg    ap_condition_354;
reg    ap_condition_227;
reg    ap_condition_372;
reg    ap_condition_689;
reg    ap_condition_419;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 vDir = 1'd0;
#0 hDir = 1'd0;
#0 x_fu_132 = 16'd0;
#0 boxVCoord_loc_1_fu_136 = 16'd0;
#0 boxHCoord_loc_1_fu_140 = 16'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_2_address0),
    .ce0(whiYuv_2_ce0_local),
    .q0(whiYuv_2_q0)
);

design_1_v_tpg_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_227)) begin
        if ((1'b1 == ap_condition_354)) begin
            ap_phi_reg_pp0_iter2_phi_ln1975_reg_336 <= 2'd1;
        end else if ((1'b1 == ap_condition_350)) begin
            ap_phi_reg_pp0_iter2_phi_ln1975_reg_336 <= select_ln1975_fu_582_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_phi_ln1975_reg_336 <= ap_phi_reg_pp0_iter1_phi_ln1975_reg_336;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_227)) begin
        if ((1'b1 == ap_condition_372)) begin
            ap_phi_reg_pp0_iter2_pix_3_reg_364 <= 8'd240;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_3_reg_364 <= ap_phi_reg_pp0_iter1_pix_3_reg_364;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_227)) begin
        if ((1'b1 == ap_condition_372)) begin
            ap_phi_reg_pp0_iter2_pix_4_reg_347 <= conv2_i_i_i129;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_4_reg_347 <= ap_phi_reg_pp0_iter1_pix_4_reg_347;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_227)) begin
        if ((1'b1 == ap_condition_372)) begin
            ap_phi_reg_pp0_iter2_pix_reg_384 <= 8'd240;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_reg_384 <= ap_phi_reg_pp0_iter1_pix_reg_384;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1942_fu_679_p2) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd1))) begin
        ap_phi_reg_pp0_iter3_pix_3_reg_364 <= pixOut_5_fu_689_p3;
    end else if (((~(patternId_val_load_read_reg_833 == 8'd2) & ~(patternId_val_load_read_reg_833 == 8'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd0) & (or_ln1963_reg_948 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln1942_fu_679_p2) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd1)))) begin
        ap_phi_reg_pp0_iter3_pix_3_reg_364 <= {{bckgndYUV_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_3_reg_364 <= ap_phi_reg_pp0_iter2_pix_3_reg_364;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1942_fu_679_p2) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd1))) begin
        ap_phi_reg_pp0_iter3_pix_4_reg_347 <= boxColorB;
    end else if (((~(patternId_val_load_read_reg_833 == 8'd2) & ~(patternId_val_load_read_reg_833 == 8'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd0) & (or_ln1963_reg_948 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln1942_fu_679_p2) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd1)))) begin
        ap_phi_reg_pp0_iter3_pix_4_reg_347 <= {{bckgndYUV_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_4_reg_347 <= ap_phi_reg_pp0_iter2_pix_4_reg_347;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1942_fu_679_p2) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd1))) begin
        ap_phi_reg_pp0_iter3_pix_reg_384 <= boxColorR;
    end else if (((~(patternId_val_load_read_reg_833 == 8'd2) & ~(patternId_val_load_read_reg_833 == 8'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd0) & (or_ln1963_reg_948 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln1942_fu_679_p2) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd1)))) begin
        ap_phi_reg_pp0_iter3_pix_reg_384 <= pixIn_fu_595_p1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_pix_reg_384 <= ap_phi_reg_pp0_iter2_pix_reg_384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            boxHCoord_loc_1_fu_140 <= boxHCoord_loc_0;
        end else if ((1'b1 == ap_condition_689)) begin
            boxHCoord_loc_1_fu_140 <= select_ln1911_fu_524_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            boxVCoord_loc_1_fu_136 <= boxVCoord_loc_0;
        end else if ((1'b1 == ap_condition_689)) begin
            boxVCoord_loc_1_fu_136 <= select_ln1915_fu_548_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_419)) begin
        if (((icmp_ln1894_fu_477_p2 == 1'd1) & (hDir_load_load_fu_462_p1 == 1'd1))) begin
            hDir <= 1'd0;
        end else if (((icmp_ln1889_fu_466_p2 == 1'd1) & (hDir_load_load_fu_462_p1 == 1'd0))) begin
            hDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_419)) begin
        if (((icmp_ln1906_fu_503_p2 == 1'd1) & (vDir_load_load_fu_488_p1 == 1'd1))) begin
            vDir <= 1'd0;
        end else if (((icmp_ln1901_fu_492_p2 == 1'd1) & (vDir_load_load_fu_488_p1 == 1'd0))) begin
            vDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_132 <= 16'd0;
        end else if (((icmp_ln774_fu_436_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_fu_132 <= x_2_fu_441_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln774_reg_911 <= icmp_ln774_fu_436_p2;
        motionSpeed_cast_reg_887[7 : 0] <= motionSpeed_cast_fu_408_p1[7 : 0];
        or_ln1963_reg_948 <= or_ln1963_fu_577_p2;
        trunc_ln774_reg_915 <= trunc_ln774_fu_447_p1;
        x_1_reg_895 <= x_fu_132;
        zext_ln1889_cast_reg_881[8 : 0] <= zext_ln1889_cast_fu_404_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_phi_ln1975_reg_336 <= ap_phi_reg_pp0_iter0_phi_ln1975_reg_336;
        ap_phi_reg_pp0_iter1_pix_3_reg_364 <= ap_phi_reg_pp0_iter0_pix_3_reg_364;
        ap_phi_reg_pp0_iter1_pix_4_reg_347 <= ap_phi_reg_pp0_iter0_pix_4_reg_347;
        ap_phi_reg_pp0_iter1_pix_reg_384 <= ap_phi_reg_pp0_iter0_pix_reg_384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        boxHCoord_loc_1_load_reg_906 <= boxHCoord_loc_1_fu_140;
        boxVCoord_loc_1_load_reg_901 <= boxVCoord_loc_1_fu_136;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln774_reg_911_pp0_iter2_reg <= icmp_ln774_reg_911;
        or_ln1963_reg_948_pp0_iter2_reg <= or_ln1963_reg_948;
    end
end

always @ (*) begin
    if (((icmp_ln774_fu_436_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1906_fu_503_p2 == 1'd0) & (vDir_load_load_fu_488_p1 == 1'd1) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)) | ((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1901_fu_492_p2 == 1'd1) & (vDir_load_load_fu_488_p1 == 1'd0) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)))) begin
        ap_phi_mux_empty_86_phi_fu_322_p8 = 1'd1;
    end else if ((((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1901_fu_492_p2 == 1'd0) & (vDir_load_load_fu_488_p1 == 1'd0) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)) | ((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1906_fu_503_p2 == 1'd1) & (vDir_load_load_fu_488_p1 == 1'd1) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)))) begin
        ap_phi_mux_empty_86_phi_fu_322_p8 = 1'd0;
    end else begin
        ap_phi_mux_empty_86_phi_fu_322_p8 = ap_phi_reg_pp0_iter1_empty_86_reg_319;
    end
end

always @ (*) begin
    if ((((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1894_fu_477_p2 == 1'd0) & (hDir_load_load_fu_462_p1 == 1'd1) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)) | ((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1889_fu_466_p2 == 1'd1) & (hDir_load_load_fu_462_p1 == 1'd0) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)))) begin
        ap_phi_mux_empty_87_phi_fu_305_p8 = 1'd1;
    end else if ((((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1889_fu_466_p2 == 1'd0) & (hDir_load_load_fu_462_p1 == 1'd0) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)) | ((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1894_fu_477_p2 == 1'd1) & (hDir_load_load_fu_462_p1 == 1'd1) & (icmp_ln1884_fu_456_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd1)))) begin
        ap_phi_mux_empty_87_phi_fu_305_p8 = 1'd0;
    end else begin
        ap_phi_mux_empty_87_phi_fu_305_p8 = ap_phi_reg_pp0_iter1_empty_87_reg_302;
    end
end

always @ (*) begin
    if ((~(color_read_reg_786 == 8'd0) & (or_ln1963_reg_948_pp0_iter2_reg == 1'd1) & (icmp_ln774_reg_911_pp0_iter2_reg == 1'd0) & (patternId_val_load_read_reg_833 == 8'd2))) begin
        ap_phi_mux_pix_3_phi_fu_368_p12 = whiYuv_2_q0;
    end else begin
        ap_phi_mux_pix_3_phi_fu_368_p12 = ap_phi_reg_pp0_iter3_pix_3_reg_364;
    end
end

always @ (*) begin
    if ((~(color_read_reg_786 == 8'd0) & (or_ln1963_reg_948_pp0_iter2_reg == 1'd1) & (icmp_ln774_reg_911_pp0_iter2_reg == 1'd0) & (patternId_val_load_read_reg_833 == 8'd2))) begin
        ap_phi_mux_pix_4_phi_fu_350_p12 = conv2_i_i_i129;
    end else begin
        ap_phi_mux_pix_4_phi_fu_350_p12 = ap_phi_reg_pp0_iter3_pix_4_reg_347;
    end
end

always @ (*) begin
    if ((~(color_read_reg_786 == 8'd0) & (or_ln1963_reg_948_pp0_iter2_reg == 1'd1) & (icmp_ln774_reg_911_pp0_iter2_reg == 1'd0) & (patternId_val_load_read_reg_833 == 8'd2))) begin
        ap_phi_mux_pix_phi_fu_388_p12 = 8'd240;
    end else begin
        ap_phi_mux_pix_phi_fu_388_p12 = ap_phi_reg_pp0_iter3_pix_reg_384;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bckgndYUV_blk_n = bckgndYUV_empty_n;
    end else begin
        bckgndYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bckgndYUV_read_local = 1'b1;
    end else begin
        bckgndYUV_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln774_fu_436_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1884_fu_456_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_833 == 8'd1))) begin
        boxHCoord_ap_vld = 1'b1;
    end else begin
        boxHCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd1) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        boxHCoord_loc_1_out_ap_vld = 1'b1;
    end else begin
        boxHCoord_loc_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln774_fu_436_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1884_fu_456_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_833 == 8'd1))) begin
        boxVCoord_ap_vld = 1'b1;
    end else begin
        boxVCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_911 == 1'd1) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        boxVCoord_loc_1_out_ap_vld = 1'b1;
    end else begin
        boxVCoord_loc_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ovrlayYUV_blk_n = ovrlayYUV_full_n;
    end else begin
        ovrlayYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ovrlayYUV_write_local = 1'b1;
    end else begin
        ovrlayYUV_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        whiYuv_2_ce0_local = 1'b1;
    end else begin
        whiYuv_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1912_fu_519_p2 = (boxHCoord_loc_1_fu_140 + motionSpeed_cast_reg_887);

assign add_ln1916_fu_543_p2 = (boxVCoord_loc_1_fu_136 + motionSpeed_cast_reg_887);

assign and_ln1942_1_fu_673_p2 = (xor_ln1932_fu_640_p2 & icmp_ln1932_1_fu_646_p2);

assign and_ln1942_2_fu_667_p2 = (xor_ln1937_fu_656_p2 & icmp_ln1937_1_fu_662_p2);

assign and_ln1942_fu_679_p2 = (and_ln1942_2_fu_667_p2 & and_ln1942_1_fu_673_p2);

assign and_ln1947_fu_685_p2 = (trunc_ln774_reg_915 & icmp);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln774_reg_911 == 1'd0) & (bckgndYUV_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (ovrlayYUV_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_227 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_350 = (~(color_read_reg_786 == 8'd1) & ~(color_read_reg_786 == 8'd0) & (icmp_ln774_fu_436_p2 == 1'd0) & (or_ln1963_fu_577_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd2));
end

always @ (*) begin
    ap_condition_354 = ((icmp_ln774_fu_436_p2 == 1'd0) & (or_ln1963_fu_577_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd2) & (color_read_reg_786 == 8'd1));
end

always @ (*) begin
    ap_condition_372 = ((icmp_ln774_fu_436_p2 == 1'd0) & (or_ln1963_fu_577_p2 == 1'd1) & (patternId_val_load_read_reg_833 == 8'd2) & (color_read_reg_786 == 8'd0));
end

always @ (*) begin
    ap_condition_419 = ((icmp_ln774_fu_436_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1884_fu_456_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_833 == 8'd1));
end

always @ (*) begin
    ap_condition_689 = ((icmp_ln774_fu_436_p2 == 1'd0) & (icmp_ln1884_fu_456_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (patternId_val_load_read_reg_833 == 8'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_phi_ln1975_reg_336 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_3_reg_364 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_4_reg_347 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_reg_384 = 'bx;

assign ap_phi_reg_pp0_iter1_empty_86_reg_319 = 'bx;

assign ap_phi_reg_pp0_iter1_empty_87_reg_302 = 'bx;

assign ap_ready = ap_ready_sig;

assign bckgndYUV_read = bckgndYUV_read_local;

assign boxBottom_fu_630_p2 = (boxSize + boxVCoord_loc_1_fu_136);

assign boxHCoord = ((ap_phi_mux_empty_87_phi_fu_305_p8[0:0] == 1'b1) ? sub_ln1914_fu_514_p2 : add_ln1912_fu_519_p2);

assign boxHCoord_loc_1_out = boxHCoord_loc_1_load_reg_906;

assign boxRight_fu_625_p2 = (boxSize + boxHCoord_loc_1_fu_140);

assign boxVCoord = ((ap_phi_mux_empty_86_phi_fu_322_p8[0:0] == 1'b1) ? sub_ln1918_fu_538_p2 : add_ln1916_fu_543_p2);

assign boxVCoord_loc_1_out = boxVCoord_loc_1_load_reg_901;

assign color_read_reg_786 = color;

assign empty_fu_735_p3 = ((tobool[0:0] == 1'b1) ? ap_phi_mux_pix_3_phi_fu_368_p12 : select_ln1991_fu_728_p3);

assign hDir_load_load_fu_462_p1 = hDir;

assign icmp_ln1884_fu_456_p2 = ((or_ln1884_fu_451_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1889_fu_466_p2 = ((boxHCoord_loc_1_fu_140 > hMax) ? 1'b1 : 1'b0);

assign icmp_ln1894_fu_477_p2 = ((zext_ln1889_cast_reg_881 > boxHCoord_loc_1_fu_140) ? 1'b1 : 1'b0);

assign icmp_ln1901_fu_492_p2 = ((boxVCoord_loc_1_fu_136 > vMax) ? 1'b1 : 1'b0);

assign icmp_ln1906_fu_503_p2 = ((zext_ln1889_cast_reg_881 > boxVCoord_loc_1_fu_136) ? 1'b1 : 1'b0);

assign icmp_ln1932_1_fu_646_p2 = ((y < boxBottom_fu_630_p2) ? 1'b1 : 1'b0);

assign icmp_ln1932_fu_635_p2 = ((y < boxVCoord_loc_1_fu_136) ? 1'b1 : 1'b0);

assign icmp_ln1937_1_fu_662_p2 = ((x_1_reg_895 < boxRight_fu_625_p2) ? 1'b1 : 1'b0);

assign icmp_ln1937_fu_651_p2 = ((x_1_reg_895 < boxHCoord_loc_1_fu_140) ? 1'b1 : 1'b0);

assign icmp_ln1963_fu_572_p2 = ((x_fu_132 == crossHairX) ? 1'b1 : 1'b0);

assign icmp_ln774_fu_436_p2 = ((x_fu_132 == loopWidth) ? 1'b1 : 1'b0);

assign motionSpeed_cast_fu_408_p1 = motionSpeed;

assign or_ln1884_fu_451_p2 = (y | x_fu_132);

assign or_ln1963_fu_577_p2 = (icmp_ln1963_fu_572_p2 | cmp2_i);

assign or_ln808_3_fu_742_p4 = {{{p_0_2_0_0_0269598_fu_714_p3}, {empty_fu_735_p3}}, {pixOut_10_fu_721_p3}};

assign ovrlayYUV_din = or_ln808_3_fu_742_p4;

assign ovrlayYUV_write = ovrlayYUV_write_local;

assign p_0_2_0_0_0269598_fu_714_p3 = ((tobool[0:0] == 1'b1) ? ap_phi_mux_pix_4_phi_fu_350_p12 : select_ln1993_fu_707_p3);

assign patternId_val_load_read_reg_833 = patternId_val_load;

assign pixIn_fu_595_p1 = bckgndYUV_dout[7:0];

assign pixOut_10_fu_721_p3 = ((tobool[0:0] == 1'b1) ? ap_phi_mux_pix_phi_fu_388_p12 : pixOut_9_fu_700_p3);

assign pixOut_5_fu_689_p3 = ((and_ln1947_fu_685_p2[0:0] == 1'b1) ? boxColorB : boxColorG);

assign pixOut_9_fu_700_p3 = ((and4_i[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_pix_phi_fu_388_p12);

assign select_ln1911_fu_524_p3 = ((ap_phi_mux_empty_87_phi_fu_305_p8[0:0] == 1'b1) ? sub_ln1914_fu_514_p2 : add_ln1912_fu_519_p2);

assign select_ln1915_fu_548_p3 = ((ap_phi_mux_empty_86_phi_fu_322_p8[0:0] == 1'b1) ? sub_ln1918_fu_538_p2 : add_ln1916_fu_543_p2);

assign select_ln1975_fu_582_p3 = ((trunc_ln774_fu_447_p1[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln1991_fu_728_p3 = ((and10_i[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_pix_3_phi_fu_368_p12);

assign select_ln1993_fu_707_p3 = ((and26_i[0:0] == 1'b1) ? 8'd0 : ap_phi_mux_pix_4_phi_fu_350_p12);

assign sub_ln1914_fu_514_p2 = (boxHCoord_loc_1_fu_140 - motionSpeed_cast_reg_887);

assign sub_ln1918_fu_538_p2 = (boxVCoord_loc_1_fu_136 - motionSpeed_cast_reg_887);

assign trunc_ln774_fu_447_p1 = x_fu_132[0:0];

assign vDir_load_load_fu_488_p1 = vDir;

assign whiYuv_2_address0 = zext_ln1975_fu_695_p1;

assign x_2_fu_441_p2 = (x_fu_132 + 16'd1);

assign xor_ln1932_fu_640_p2 = (icmp_ln1932_fu_635_p2 ^ 1'd1);

assign xor_ln1937_fu_656_p2 = (icmp_ln1937_fu_651_p2 ^ 1'd1);

assign zext_ln1889_cast_fu_404_p1 = zext_ln1889;

assign zext_ln1975_fu_695_p1 = ap_phi_reg_pp0_iter2_phi_ln1975_reg_336;

always @ (posedge ap_clk) begin
    zext_ln1889_cast_reg_881[15:9] <= 7'b0000000;
    motionSpeed_cast_reg_887[15:8] <= 8'b00000000;
end

endmodule //design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2
