// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        height_val,
        width_val,
        patternId_val,
        ZplateHorContStart_val,
        ZplateHorContDelta_val,
        ZplateVerContStart_val,
        ZplateVerContDelta_val,
        dpDynamicRange_val,
        dpYUVCoef_val,
        motionSpeed_val,
        colorFormat_val,
        bckgndYUV_din,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_full_n,
        bckgndYUV_write,
        height_val4_c3_din,
        height_val4_c3_num_data_valid,
        height_val4_c3_fifo_cap,
        height_val4_c3_full_n,
        height_val4_c3_write,
        width_val7_c4_din,
        width_val7_c4_num_data_valid,
        width_val7_c4_fifo_cap,
        width_val7_c4_full_n,
        width_val7_c4_write,
        motionSpeed_val14_c_din,
        motionSpeed_val14_c_num_data_valid,
        motionSpeed_val14_c_fifo_cap,
        motionSpeed_val14_c_full_n,
        motionSpeed_val14_c_write,
        colorFormat_val17_c5_din,
        colorFormat_val17_c5_num_data_valid,
        colorFormat_val17_c5_fifo_cap,
        colorFormat_val17_c5_full_n,
        colorFormat_val17_c5_write,
        s
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] height_val;
input  [15:0] width_val;
input  [7:0] patternId_val;
input  [15:0] ZplateHorContStart_val;
input  [15:0] ZplateHorContDelta_val;
input  [15:0] ZplateVerContStart_val;
input  [15:0] ZplateVerContDelta_val;
input  [7:0] dpDynamicRange_val;
input  [7:0] dpYUVCoef_val;
input  [7:0] motionSpeed_val;
input  [7:0] colorFormat_val;
output  [23:0] bckgndYUV_din;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
output  [15:0] height_val4_c3_din;
input  [2:0] height_val4_c3_num_data_valid;
input  [2:0] height_val4_c3_fifo_cap;
input   height_val4_c3_full_n;
output   height_val4_c3_write;
output  [15:0] width_val7_c4_din;
input  [2:0] width_val7_c4_num_data_valid;
input  [2:0] width_val7_c4_fifo_cap;
input   width_val7_c4_full_n;
output   width_val7_c4_write;
output  [7:0] motionSpeed_val14_c_din;
input  [2:0] motionSpeed_val14_c_num_data_valid;
input  [2:0] motionSpeed_val14_c_fifo_cap;
input   motionSpeed_val14_c_full_n;
output   motionSpeed_val14_c_write;
output  [7:0] colorFormat_val17_c5_din;
input  [2:0] colorFormat_val17_c5_num_data_valid;
input  [2:0] colorFormat_val17_c5_fifo_cap;
input   colorFormat_val17_c5_full_n;
output   colorFormat_val17_c5_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bckgndYUV_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] rampStart;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] hBarSel_4_0;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] hBarSel_0;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] hBarSel_3_0;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] hBarSel_5_0;
reg    height_val4_c3_blk_n;
reg    width_val7_c4_blk_n;
reg    motionSpeed_val14_c_blk_n;
reg    colorFormat_val17_c5_blk_n;
reg    ap_block_state1;
wire   [0:0] cmp2_i_fu_663_p2;
reg   [0:0] cmp2_i_reg_1308;
wire   [7:0] conv2_i_i10_i236_fu_669_p3;
reg   [7:0] conv2_i_i10_i236_reg_1313;
wire   [0:0] not_cmp2_i_fu_677_p2;
reg   [0:0] not_cmp2_i_reg_1318;
wire   [7:0] conv2_i_i10_i239_fu_683_p3;
reg   [7:0] conv2_i_i10_i239_reg_1323;
wire   [4:0] conv2_i_i_i240_cast_cast_fu_691_p3;
reg   [4:0] conv2_i_i_i240_cast_cast_reg_1328;
wire   [2:0] conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3;
reg   [2:0] conv2_i_i10_i254_cast_cast_cast_cast_reg_1333;
wire   [7:0] conv2_i_i_i255_fu_707_p3;
reg   [7:0] conv2_i_i_i255_reg_1338;
wire   [7:0] conv2_i_i_i268_fu_715_p3;
reg   [7:0] conv2_i_i_i268_reg_1343;
wire   [7:0] conv2_i_i_i282_fu_723_p3;
reg   [7:0] conv2_i_i_i282_reg_1348;
reg   [10:0] barWidth_reg_1353;
wire   [9:0] barWidthMinSamples_fu_771_p2;
reg   [9:0] barWidthMinSamples_reg_1359;
wire   [0:0] icmp_fu_801_p2;
reg   [0:0] icmp_reg_1364;
wire   [10:0] sub_i_i_i_fu_821_p2;
reg   [10:0] sub_i_i_i_reg_1369;
reg   [7:0] rampStart_load_reg_1374;
wire   [7:0] cond_i235_fu_831_p3;
reg   [7:0] cond_i235_reg_1380;
wire   [7:0] empty_94_fu_843_p1;
reg   [7:0] empty_94_reg_1385;
wire   [15:0] shl_i_fu_847_p3;
reg   [15:0] shl_i_reg_1390;
wire   [16:0] sub35_i_fu_855_p2;
reg   [16:0] sub35_i_reg_1395;
wire   [16:0] sub10_i_fu_861_p2;
reg   [16:0] sub10_i_reg_1400;
wire   [0:0] cmp54_i_fu_867_p2;
reg   [0:0] cmp54_i_reg_1405;
wire   [0:0] cmp121_i_fu_873_p2;
reg   [0:0] cmp121_i_reg_1410;
wire   [0:0] cmp136_i_fu_879_p2;
reg   [0:0] cmp136_i_reg_1415;
reg   [15:0] y_3_reg_1420;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp12_i_fu_1041_p2;
reg   [0:0] cmp12_i_reg_1428;
reg   [1:0] Sel_reg_1433;
wire   [0:0] cmp_i34_fu_1063_p2;
reg   [0:0] cmp_i34_reg_1438;
wire   [0:0] cmp11_i_fu_1070_p2;
reg   [0:0] cmp11_i_reg_1443;
wire   [7:0] add_i349_fu_1076_p2;
reg   [7:0] add_i349_reg_1448;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_ready;
wire   [23:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_452_p4;
reg   [0:0] rampVal_3_flag_0_reg_448;
wire    ap_CS_fsm_state4;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_464_p4;
reg   [0:0] hdata_flag_0_reg_460;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_476_p4;
reg   [0:0] rampVal_2_flag_0_reg_472;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg;
wire   [0:0] icmp_ln563_fu_1026_p2;
wire    ap_CS_fsm_state3;
reg   [15:0] rampVal_3_new_0_fu_334;
reg   [15:0] rampVal_3_loc_0_fu_330;
reg   [15:0] rampVal_loc_0_fu_326;
reg   [7:0] hBarSel_4_0_loc_0_fu_322;
reg   [15:0] zonePlateVAddr_loc_0_fu_318;
reg   [7:0] vBarSel_loc_0_fu_314;
reg   [7:0] hBarSel_0_loc_0_fu_310;
reg   [15:0] hdata_new_0_fu_306;
reg   [15:0] hdata_loc_0_fu_302;
reg   [7:0] vBarSel_2_loc_0_fu_298;
reg   [7:0] hBarSel_3_0_loc_0_fu_294;
reg   [15:0] rampVal_2_new_0_fu_290;
reg   [15:0] rampVal_2_loc_0_fu_286;
reg   [7:0] vBarSel_3_loc_0_fu_282;
reg   [7:0] hBarSel_5_0_loc_0_fu_278;
reg   [7:0] outpix_0_2_0_0_0_load217_lcssa226_fu_270;
reg   [7:0] outpix_0_1_0_0_0_load215_lcssa223_fu_266;
reg   [7:0] outpix_0_0_0_0_0_load213_lcssa220_fu_262;
wire   [7:0] add_ln750_fu_1087_p2;
reg   [15:0] y_fu_274;
wire   [15:0] add_ln563_fu_1031_p2;
wire   [7:0] zext_ln563_fu_953_p1;
wire   [7:0] zext_ln1775_fu_945_p1;
wire   [7:0] zext_ln1664_fu_933_p1;
wire   [7:0] zext_ln1545_fu_917_p1;
wire   [7:0] zext_ln1412_fu_909_p1;
wire   [15:0] zext_ln1257_fu_893_p1;
reg    colorFormat_val17_c5_write_local;
reg    motionSpeed_val14_c_write_local;
reg    width_val7_c4_write_local;
reg    height_val4_c3_write_local;
wire   [13:0] empty_fu_735_p1;
wire   [13:0] add_i_fu_739_p2;
wire   [13:0] add2_i_fu_755_p2;
wire   [9:0] p_cast_fu_761_p4;
wire   [13:0] empty_93_fu_781_p1;
wire   [6:0] tmp_fu_791_p4;
wire   [13:0] add5_i_fu_785_p2;
wire   [9:0] tmp_1_fu_807_p4;
wire   [10:0] barHeight_cast_fu_817_p1;
wire   [16:0] width_val_cast14_fu_731_p1;
wire   [16:0] height_val_cast15_fu_777_p1;
wire   [16:0] zext_ln563_1_fu_1037_p1;
wire   [7:0] empty_95_fu_1048_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 hBarSel_4_0 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 hBarSel_0 = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 hBarSel_3_0 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 hBarSel_5_0 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg = 1'b0;
#0 rampVal_3_loc_0_fu_330 = 16'd0;
#0 rampVal_loc_0_fu_326 = 16'd0;
#0 hBarSel_4_0_loc_0_fu_322 = 8'd0;
#0 zonePlateVAddr_loc_0_fu_318 = 16'd0;
#0 vBarSel_loc_0_fu_314 = 8'd0;
#0 hBarSel_0_loc_0_fu_310 = 8'd0;
#0 hdata_loc_0_fu_302 = 16'd0;
#0 vBarSel_2_loc_0_fu_298 = 8'd0;
#0 hBarSel_3_0_loc_0_fu_294 = 8'd0;
#0 rampVal_2_loc_0_fu_286 = 16'd0;
#0 vBarSel_3_loc_0_fu_282 = 8'd0;
#0 hBarSel_5_0_loc_0_fu_278 = 8'd0;
#0 y_fu_274 = 16'd0;
end

design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_din),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_448),
    .hdata_flag_0(hdata_flag_0_reg_460),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_472),
    .width_val(width_val),
    .conv2_i_i_i282(conv2_i_i_i282_reg_1348),
    .conv2_i_i_i268(conv2_i_i_i268_reg_1343),
    .conv2_i_i_i255(conv2_i_i_i255_reg_1338),
    .conv2_i_i_i240_cast_cast(conv2_i_i_i240_cast_cast_reg_1328),
    .conv2_i_i_i_cast(not_cmp2_i_reg_1318),
    .cond_i235(cond_i235_reg_1380),
    .conv2_i_i10_i254_cast_cast_cast_cast(conv2_i_i10_i254_cast_cast_cast_cast_reg_1333),
    .conv2_i_i10_i239(conv2_i_i10_i239_reg_1323),
    .conv2_i_i10_i236(conv2_i_i10_i236_reg_1313),
    .rampStart_1(rampStart_load_reg_1374),
    .ZplateHorContStart_val(ZplateHorContStart_val),
    .patternId_val(patternId_val),
    .cmp2_i(cmp2_i_reg_1308),
    .conv2_i_i10_i233_cast(rampStart_load_reg_1374),
    .y(y_3_reg_1420),
    .colorFormat_val(colorFormat_val),
    .empty(empty_94_reg_1385),
    .barWidth_cast(barWidth_reg_1353),
    .barWidth(barWidth_reg_1353),
    .shl_i(shl_i_reg_1390),
    .ZplateHorContDelta_val(ZplateHorContDelta_val),
    .ZplateVerContStart_val(ZplateVerContStart_val),
    .cmp12_i(cmp12_i_reg_1428),
    .ZplateVerContDelta_val(ZplateVerContDelta_val),
    .sub_i_i_i(sub_i_i_i_reg_1369),
    .barWidthMinSamples(barWidthMinSamples_reg_1359),
    .cmp11_i(cmp11_i_reg_1443),
    .cmp_i34(cmp_i34_reg_1438),
    .sub35_i(sub35_i_reg_1395),
    .add_i349(add_i349_reg_1448),
    .icmp(icmp_reg_1364),
    .Sel_cast(Sel_reg_1433),
    .cmp54_i(cmp54_i_reg_1405),
    .cmp136_i(cmp136_i_reg_1415),
    .cmp121_i(cmp121_i_reg_1410),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_330),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_326),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_4_0_loc_1_out_i(hBarSel_4_0_loc_0_fu_322),
    .hBarSel_4_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o),
    .hBarSel_4_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_318),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_314),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o_ap_vld),
    .hBarSel_0_loc_1_out_i(hBarSel_0_loc_0_fu_310),
    .hBarSel_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o),
    .hBarSel_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_302),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_298),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o_ap_vld),
    .hBarSel_3_0_loc_1_out_i(hBarSel_3_0_loc_0_fu_294),
    .hBarSel_3_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o),
    .hBarSel_3_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_286),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_282),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o_ap_vld),
    .hBarSel_5_0_loc_1_out_i(hBarSel_5_0_loc_0_fu_278),
    .hBarSel_5_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o),
    .hBarSel_5_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o_ap_vld),
    .outpix_0_2_0_0_0_load216_out_i(outpix_0_2_0_0_0_load217_lcssa226_fu_270),
    .outpix_0_2_0_0_0_load216_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o),
    .outpix_0_2_0_0_0_load216_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o_ap_vld),
    .outpix_0_1_0_0_0_load214_out_i(outpix_0_1_0_0_0_load215_lcssa223_fu_266),
    .outpix_0_1_0_0_0_load214_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o),
    .outpix_0_1_0_0_0_load214_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o_ap_vld),
    .outpix_0_0_0_0_0_load212_out_i(outpix_0_0_0_0_0_load213_lcssa220_fu_262),
    .outpix_0_0_0_0_0_load212_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o),
    .outpix_0_0_0_0_0_load212_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_ap_vld),
    .hBarSel_4_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0),
    .hBarSel_4_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_ap_vld),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_ap_vld),
    .hBarSel_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0),
    .hBarSel_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_ap_vld),
    .hBarSel_3_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0),
    .hBarSel_3_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_ap_vld),
    .hBarSel_5_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0),
    .hBarSel_5_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln563_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln563_fu_1026_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_0_loc_0_fu_310 <= zext_ln1545_fu_917_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_0_loc_0_fu_310 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_3_0_loc_0_fu_294 <= zext_ln1664_fu_933_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_3_0_loc_0_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_4_0_loc_0_fu_322 <= hBarSel_4_0;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_4_0_loc_0_fu_322 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_5_0_loc_0_fu_278 <= zext_ln563_fu_953_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_5_0_loc_0_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hdata_flag_0_reg_460 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hdata_flag_0_reg_460 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hdata_loc_0_fu_302 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_loc_0_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_2_flag_0_reg_472 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_2_flag_0_reg_472 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_2_loc_0_fu_286 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_loc_0_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_3_flag_0_reg_448 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_3_flag_0_reg_448 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_3_loc_0_fu_330 <= rampVal_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_3_loc_0_fu_330 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_loc_0_fu_326 <= zext_ln1257_fu_893_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_loc_0_fu_326 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_2_loc_0_fu_298 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_2_loc_0_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_3_loc_0_fu_282 <= zext_ln1775_fu_945_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_3_loc_0_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_loc_0_fu_314 <= zext_ln1412_fu_909_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_loc_0_fu_314 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_fu_274 <= 16'd0;
    end else if (((icmp_ln563_fu_1026_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_274 <= add_ln563_fu_1031_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        zonePlateVAddr_loc_0_fu_318 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVAddr_loc_0_fu_318 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Sel_reg_1433 <= {{y_fu_274[7:6]}};
        add_i349_reg_1448 <= add_i349_fu_1076_p2;
        cmp11_i_reg_1443 <= cmp11_i_fu_1070_p2;
        cmp12_i_reg_1428 <= cmp12_i_fu_1041_p2;
        cmp_i34_reg_1438 <= cmp_i34_fu_1063_p2;
        y_3_reg_1420 <= y_fu_274;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        barWidthMinSamples_reg_1359 <= barWidthMinSamples_fu_771_p2;
        barWidth_reg_1353 <= {{add_i_fu_739_p2[13:3]}};
        cmp121_i_reg_1410 <= cmp121_i_fu_873_p2;
        cmp136_i_reg_1415 <= cmp136_i_fu_879_p2;
        cmp2_i_reg_1308 <= cmp2_i_fu_663_p2;
        cmp54_i_reg_1405 <= cmp54_i_fu_867_p2;
        cond_i235_reg_1380 <= cond_i235_fu_831_p3;
        conv2_i_i10_i236_reg_1313[1 : 0] <= conv2_i_i10_i236_fu_669_p3[1 : 0];
conv2_i_i10_i236_reg_1313[5 : 4] <= conv2_i_i10_i236_fu_669_p3[5 : 4];
conv2_i_i10_i236_reg_1313[7] <= conv2_i_i10_i236_fu_669_p3[7];
        conv2_i_i10_i239_reg_1323[0] <= conv2_i_i10_i239_fu_683_p3[0];
conv2_i_i10_i239_reg_1323[2] <= conv2_i_i10_i239_fu_683_p3[2];
conv2_i_i10_i239_reg_1323[4] <= conv2_i_i10_i239_fu_683_p3[4];
conv2_i_i10_i239_reg_1323[7] <= conv2_i_i10_i239_fu_683_p3[7];
        conv2_i_i10_i254_cast_cast_cast_cast_reg_1333[0] <= conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3[0];
conv2_i_i10_i254_cast_cast_cast_cast_reg_1333[2] <= conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3[2];
        conv2_i_i_i240_cast_cast_reg_1328[0] <= conv2_i_i_i240_cast_cast_fu_691_p3[0];
conv2_i_i_i240_cast_cast_reg_1328[2] <= conv2_i_i_i240_cast_cast_fu_691_p3[2];
conv2_i_i_i240_cast_cast_reg_1328[4] <= conv2_i_i_i240_cast_cast_fu_691_p3[4];
        conv2_i_i_i255_reg_1338[2] <= conv2_i_i_i255_fu_707_p3[2];
conv2_i_i_i255_reg_1338[4] <= conv2_i_i_i255_fu_707_p3[4];
conv2_i_i_i255_reg_1338[7] <= conv2_i_i_i255_fu_707_p3[7];
        conv2_i_i_i268_reg_1343[7] <= conv2_i_i_i268_fu_715_p3[7];
        conv2_i_i_i282_reg_1348[6 : 0] <= conv2_i_i_i282_fu_723_p3[6 : 0];
        empty_94_reg_1385 <= empty_94_fu_843_p1;
        icmp_reg_1364 <= icmp_fu_801_p2;
        not_cmp2_i_reg_1318 <= not_cmp2_i_fu_677_p2;
        rampStart_load_reg_1374 <= rampStart;
        shl_i_reg_1390[15 : 8] <= shl_i_fu_847_p3[15 : 8];
        sub10_i_reg_1400 <= sub10_i_fu_861_p2;
        sub35_i_reg_1395 <= sub35_i_fu_855_p2;
        sub_i_i_i_reg_1369 <= sub_i_i_i_fu_821_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1026_p2 == 1'd1) & (ap_phi_mux_hdata_flag_0_phi_fu_464_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        hdata <= hdata_new_0_fu_306;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_new_0_fu_306 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        outpix_0_0_0_0_0_load213_lcssa220_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        outpix_0_1_0_0_0_load215_lcssa223_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        outpix_0_2_0_0_0_load217_lcssa226_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampStart <= add_ln750_fu_1087_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1026_p2 == 1'd1) & (ap_phi_mux_rampVal_3_flag_0_phi_fu_452_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampVal_1 <= rampVal_3_new_0_fu_334;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_1026_p2 == 1'd1) & (ap_phi_mux_rampVal_2_flag_0_phi_fu_476_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampVal_2 <= rampVal_2_new_0_fu_290;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_new_0_fu_290 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_3_new_0_fu_334 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln563_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln563_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val17_c5_blk_n = colorFormat_val17_c5_full_n;
    end else begin
        colorFormat_val17_c5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        colorFormat_val17_c5_write_local = 1'b1;
    end else begin
        colorFormat_val17_c5_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c3_blk_n = height_val4_c3_full_n;
    end else begin
        height_val4_c3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        height_val4_c3_write_local = 1'b1;
    end else begin
        height_val4_c3_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val14_c_blk_n = motionSpeed_val14_c_full_n;
    end else begin
        motionSpeed_val14_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        motionSpeed_val14_c_write_local = 1'b1;
    end else begin
        motionSpeed_val14_c_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val7_c4_blk_n = width_val7_c4_full_n;
    end else begin
        width_val7_c4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        width_val7_c4_write_local = 1'b1;
    end else begin
        width_val7_c4_write_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln563_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2_i_fu_755_p2 = (empty_fu_735_p1 + 14'd15);

assign add5_i_fu_785_p2 = (empty_93_fu_781_p1 + 14'd15);

assign add_i349_fu_1076_p2 = (rampStart + empty_95_fu_1048_p1);

assign add_i_fu_739_p2 = (empty_fu_735_p1 + 14'd7);

assign add_ln563_fu_1031_p2 = (y_fu_274 + 16'd1);

assign add_ln750_fu_1087_p2 = (rampStart + motionSpeed_val);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (colorFormat_val17_c5_full_n == 1'b0) | (motionSpeed_val14_c_full_n == 1'b0) | (width_val7_c4_full_n == 1'b0) | (height_val4_c3_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_464_p4 = hdata_flag_0_reg_460;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_476_p4 = rampVal_2_flag_0_reg_472;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_452_p4 = rampVal_3_flag_0_reg_448;

assign barHeight_cast_fu_817_p1 = tmp_1_fu_807_p4;

assign barWidthMinSamples_fu_771_p2 = ($signed(p_cast_fu_761_p4) + $signed(10'd1023));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_din;

assign cmp11_i_fu_1070_p2 = ((sub10_i_reg_1400 == zext_ln563_1_fu_1037_p1) ? 1'b1 : 1'b0);

assign cmp121_i_fu_873_p2 = ((dpYUVCoef_val == 8'd0) ? 1'b1 : 1'b0);

assign cmp12_i_fu_1041_p2 = ((y_fu_274 != 16'd0) ? 1'b1 : 1'b0);

assign cmp136_i_fu_879_p2 = ((colorFormat_val != 8'd1) ? 1'b1 : 1'b0);

assign cmp2_i_fu_663_p2 = ((colorFormat_val == 8'd0) ? 1'b1 : 1'b0);

assign cmp54_i_fu_867_p2 = ((dpDynamicRange_val == 8'd0) ? 1'b1 : 1'b0);

assign cmp_i34_fu_1063_p2 = ((y_fu_274 == 16'd0) ? 1'b1 : 1'b0);

assign colorFormat_val17_c5_din = colorFormat_val;

assign colorFormat_val17_c5_write = colorFormat_val17_c5_write_local;

assign cond_i235_fu_831_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? rampStart : 8'd128);

assign conv2_i_i10_i236_fu_669_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? 8'd255 : 8'd76);

assign conv2_i_i10_i239_fu_683_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? 8'd0 : 8'd149);

assign conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? 3'd0 : 3'd5);

assign conv2_i_i_i240_cast_cast_fu_691_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? 5'd0 : 5'd21);

assign conv2_i_i_i255_fu_707_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? 8'd255 : 8'd107);

assign conv2_i_i_i268_fu_715_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign conv2_i_i_i282_fu_723_p3 = ((cmp2_i_fu_663_p2[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign empty_93_fu_781_p1 = height_val[13:0];

assign empty_94_fu_843_p1 = s[7:0];

assign empty_95_fu_1048_p1 = y_fu_274[7:0];

assign empty_fu_735_p1 = width_val[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg;

assign height_val4_c3_din = height_val;

assign height_val4_c3_write = height_val4_c3_write_local;

assign height_val_cast15_fu_777_p1 = height_val;

assign icmp_fu_801_p2 = ((tmp_fu_791_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln563_fu_1026_p2 = ((y_fu_274 == height_val) ? 1'b1 : 1'b0);

assign motionSpeed_val14_c_din = motionSpeed_val;

assign motionSpeed_val14_c_write = motionSpeed_val14_c_write_local;

assign not_cmp2_i_fu_677_p2 = (cmp2_i_fu_663_p2 ^ 1'd1);

assign p_cast_fu_761_p4 = {{add2_i_fu_755_p2[13:4]}};

assign shl_i_fu_847_p3 = {{rampStart}, {8'd0}};

assign sub10_i_fu_861_p2 = ($signed(height_val_cast15_fu_777_p1) + $signed(17'd131071));

assign sub35_i_fu_855_p2 = ($signed(width_val_cast14_fu_731_p1) + $signed(17'd131071));

assign sub_i_i_i_fu_821_p2 = ($signed(barHeight_cast_fu_817_p1) + $signed(11'd2047));

assign tmp_1_fu_807_p4 = {{add5_i_fu_785_p2[13:4]}};

assign tmp_fu_791_p4 = {{colorFormat_val[7:1]}};

assign width_val7_c4_din = width_val;

assign width_val7_c4_write = width_val7_c4_write_local;

assign width_val_cast14_fu_731_p1 = width_val;

assign zext_ln1257_fu_893_p1 = rampVal;

assign zext_ln1412_fu_909_p1 = vBarSel;

assign zext_ln1545_fu_917_p1 = hBarSel_0;

assign zext_ln1664_fu_933_p1 = hBarSel_3_0;

assign zext_ln1775_fu_945_p1 = vBarSel_1;

assign zext_ln563_1_fu_1037_p1 = y_fu_274;

assign zext_ln563_fu_953_p1 = hBarSel_5_0;

always @ (posedge ap_clk) begin
    conv2_i_i10_i236_reg_1313[3:2] <= 2'b11;
    conv2_i_i10_i236_reg_1313[6] <= 1'b1;
    conv2_i_i10_i239_reg_1323[1] <= 1'b0;
    conv2_i_i10_i239_reg_1323[3:3] <= 1'b0;
    conv2_i_i10_i239_reg_1323[6:5] <= 2'b00;
    conv2_i_i_i240_cast_cast_reg_1328[1] <= 1'b0;
    conv2_i_i_i240_cast_cast_reg_1328[3] <= 1'b0;
    conv2_i_i10_i254_cast_cast_cast_cast_reg_1333[1] <= 1'b0;
    conv2_i_i_i255_reg_1338[1:0] <= 2'b11;
    conv2_i_i_i255_reg_1338[3:3] <= 1'b1;
    conv2_i_i_i255_reg_1338[6:5] <= 2'b11;
    conv2_i_i_i268_reg_1343[6:0] <= 7'b0000000;
    conv2_i_i_i282_reg_1348[7] <= 1'b1;
    shl_i_reg_1390[7:0] <= 8'b00000000;
end

endmodule //design_1_v_tpg_0_0_tpgBackground
