-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    boxHCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorB : IN STD_LOGIC_VECTOR (7 downto 0);
    conv2_i_i_i129 : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorR : IN STD_LOGIC_VECTOR (7 downto 0);
    and4_i : IN STD_LOGIC_VECTOR (0 downto 0);
    and26_i : IN STD_LOGIC_VECTOR (0 downto 0);
    tobool : IN STD_LOGIC_VECTOR (0 downto 0);
    and10_i : IN STD_LOGIC_VECTOR (0 downto 0);
    patternId_val_load : IN STD_LOGIC_VECTOR (7 downto 0);
    boxSize : IN STD_LOGIC_VECTOR (15 downto 0);
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    vMax : IN STD_LOGIC_VECTOR (15 downto 0);
    hMax : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1889 : IN STD_LOGIC_VECTOR (8 downto 0);
    icmp : IN STD_LOGIC_VECTOR (0 downto 0);
    boxColorG : IN STD_LOGIC_VECTOR (7 downto 0);
    crossHairX : IN STD_LOGIC_VECTOR (15 downto 0);
    cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    boxHCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxVCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_ap_vld : OUT STD_LOGIC;
    boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_ap_vld : OUT STD_LOGIC );
end;


architecture behav of design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln774_reg_911 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln774_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal vDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal whiYuv_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bckgndYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal color_read_reg_786 : STD_LOGIC_VECTOR (7 downto 0);
    signal patternId_val_load_read_reg_833 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1889_cast_fu_404_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1889_cast_reg_881 : STD_LOGIC_VECTOR (15 downto 0);
    signal motionSpeed_cast_fu_408_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal motionSpeed_cast_reg_887 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_reg_895 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxVCoord_loc_1_load_reg_901 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxHCoord_loc_1_load_reg_906 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln774_reg_911_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln774_fu_447_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln774_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1884_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hDir_load_load_fu_462_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1889_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1894_fu_477_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vDir_load_load_fu_488_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1901_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1906_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_reg_948 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_reg_948_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1975_fu_582_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal pixIn_fu_595_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln1942_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_5_fu_689_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_87_phi_fu_305_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_87_reg_302 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_86_phi_fu_322_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_86_reg_319 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_phi_ln1975_reg_336 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln1975_reg_336 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter2_phi_ln1975_reg_336 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_pix_4_phi_fu_350_p12 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_4_reg_347 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_4_reg_347 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_4_reg_347 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_4_reg_347 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_3_phi_fu_368_p12 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_3_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_3_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_3_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_3_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_pix_phi_fu_388_p12 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_reg_384 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1975_fu_695_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal select_ln1911_fu_524_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1915_fu_548_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_fu_132 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal x_2_fu_441_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal boxVCoord_loc_1_fu_136 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal boxHCoord_loc_1_fu_140 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal bckgndYUV_read_local : STD_LOGIC;
    signal or_ln808_3_fu_742_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ovrlayYUV_write_local : STD_LOGIC;
    signal whiYuv_2_ce0_local : STD_LOGIC;
    signal or_ln1884_fu_451_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1914_fu_514_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1912_fu_519_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1918_fu_538_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1916_fu_543_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1963_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1932_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxBottom_fu_630_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1937_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxRight_fu_625_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1937_1_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1937_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1932_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1932_1_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1942_1_fu_673_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1942_2_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1947_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1993_fu_707_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_9_fu_700_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1991_fu_728_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_2_0_0_0269598_fu_714_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_735_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_10_fu_721_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_350 : BOOLEAN;
    signal ap_condition_354 : BOOLEAN;
    signal ap_condition_227 : BOOLEAN;
    signal ap_condition_372 : BOOLEAN;
    signal ap_condition_689 : BOOLEAN;
    signal ap_condition_419 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component design_1_v_tpg_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    whiYuv_2_U : component design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_2_address0,
        ce0 => whiYuv_2_ce0_local,
        q0 => whiYuv_2_q0);

    flow_control_loop_pipe_sequential_init_U : component design_1_v_tpg_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_phi_ln1975_reg_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_354)) then 
                    ap_phi_reg_pp0_iter2_phi_ln1975_reg_336 <= ap_const_lv2_1;
                elsif ((ap_const_boolean_1 = ap_condition_350)) then 
                    ap_phi_reg_pp0_iter2_phi_ln1975_reg_336 <= select_ln1975_fu_582_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_phi_ln1975_reg_336 <= ap_phi_reg_pp0_iter1_phi_ln1975_reg_336;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_3_reg_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_372)) then 
                    ap_phi_reg_pp0_iter2_pix_3_reg_364 <= ap_const_lv8_F0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_3_reg_364 <= ap_phi_reg_pp0_iter1_pix_3_reg_364;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_4_reg_347_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_372)) then 
                    ap_phi_reg_pp0_iter2_pix_4_reg_347 <= conv2_i_i_i129;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_4_reg_347 <= ap_phi_reg_pp0_iter1_pix_4_reg_347;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_reg_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_372)) then 
                    ap_phi_reg_pp0_iter2_pix_reg_384 <= ap_const_lv8_F0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_reg_384 <= ap_phi_reg_pp0_iter1_pix_reg_384;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_3_reg_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln1942_fu_679_p2) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_364 <= pixOut_5_fu_689_p3;
            elsif (((not((patternId_val_load_read_reg_833 = ap_const_lv8_2)) and not((patternId_val_load_read_reg_833 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (or_ln1963_reg_948 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1942_fu_679_p2) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_364 <= bckgndYUV_dout(15 downto 8);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_364 <= ap_phi_reg_pp0_iter2_pix_3_reg_364;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_4_reg_347_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln1942_fu_679_p2) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_347 <= boxColorB;
            elsif (((not((patternId_val_load_read_reg_833 = ap_const_lv8_2)) and not((patternId_val_load_read_reg_833 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (or_ln1963_reg_948 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1942_fu_679_p2) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_347 <= bckgndYUV_dout(23 downto 16);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_347 <= ap_phi_reg_pp0_iter2_pix_4_reg_347;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_reg_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln1942_fu_679_p2) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_reg_384 <= boxColorR;
            elsif (((not((patternId_val_load_read_reg_833 = ap_const_lv8_2)) and not((patternId_val_load_read_reg_833 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (or_ln1963_reg_948 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1942_fu_679_p2) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_reg_384 <= pixIn_fu_595_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_reg_384 <= ap_phi_reg_pp0_iter2_pix_reg_384;
            end if; 
        end if;
    end process;

    boxHCoord_loc_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxHCoord_loc_1_fu_140 <= boxHCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_689)) then 
                    boxHCoord_loc_1_fu_140 <= select_ln1911_fu_524_p3;
                end if;
            end if; 
        end if;
    end process;

    boxVCoord_loc_1_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxVCoord_loc_1_fu_136 <= boxVCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_689)) then 
                    boxVCoord_loc_1_fu_136 <= select_ln1915_fu_548_p3;
                end if;
            end if; 
        end if;
    end process;

    hDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_419)) then
                if (((icmp_ln1894_fu_477_p2 = ap_const_lv1_1) and (hDir_load_load_fu_462_p1 = ap_const_lv1_1))) then 
                    hDir <= ap_const_lv1_0;
                elsif (((icmp_ln1889_fu_466_p2 = ap_const_lv1_1) and (hDir_load_load_fu_462_p1 = ap_const_lv1_0))) then 
                    hDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    vDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_419)) then
                if (((icmp_ln1906_fu_503_p2 = ap_const_lv1_1) and (vDir_load_load_fu_488_p1 = ap_const_lv1_1))) then 
                    vDir <= ap_const_lv1_0;
                elsif (((icmp_ln1901_fu_492_p2 = ap_const_lv1_1) and (vDir_load_load_fu_488_p1 = ap_const_lv1_0))) then 
                    vDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    x_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_132 <= ap_const_lv16_0;
                elsif (((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    x_fu_132 <= x_2_fu_441_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln774_reg_911 <= icmp_ln774_fu_436_p2;
                    motionSpeed_cast_reg_887(7 downto 0) <= motionSpeed_cast_fu_408_p1(7 downto 0);
                or_ln1963_reg_948 <= or_ln1963_fu_577_p2;
                trunc_ln774_reg_915 <= trunc_ln774_fu_447_p1;
                x_1_reg_895 <= x_fu_132;
                    zext_ln1889_cast_reg_881(8 downto 0) <= zext_ln1889_cast_fu_404_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_phi_ln1975_reg_336 <= ap_phi_reg_pp0_iter0_phi_ln1975_reg_336;
                ap_phi_reg_pp0_iter1_pix_3_reg_364 <= ap_phi_reg_pp0_iter0_pix_3_reg_364;
                ap_phi_reg_pp0_iter1_pix_4_reg_347 <= ap_phi_reg_pp0_iter0_pix_4_reg_347;
                ap_phi_reg_pp0_iter1_pix_reg_384 <= ap_phi_reg_pp0_iter0_pix_reg_384;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                boxHCoord_loc_1_load_reg_906 <= boxHCoord_loc_1_fu_140;
                boxVCoord_loc_1_load_reg_901 <= boxVCoord_loc_1_fu_136;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln774_reg_911_pp0_iter2_reg <= icmp_ln774_reg_911;
                or_ln1963_reg_948_pp0_iter2_reg <= or_ln1963_reg_948;
            end if;
        end if;
    end process;
    zext_ln1889_cast_reg_881(15 downto 9) <= "0000000";
    motionSpeed_cast_reg_887(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1912_fu_519_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_fu_140) + unsigned(motionSpeed_cast_reg_887));
    add_ln1916_fu_543_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_fu_136) + unsigned(motionSpeed_cast_reg_887));
    and_ln1942_1_fu_673_p2 <= (xor_ln1932_fu_640_p2 and icmp_ln1932_1_fu_646_p2);
    and_ln1942_2_fu_667_p2 <= (xor_ln1937_fu_656_p2 and icmp_ln1937_1_fu_662_p2);
    and_ln1942_fu_679_p2 <= (and_ln1942_2_fu_667_p2 and and_ln1942_1_fu_673_p2);
    and_ln1947_fu_685_p2 <= (trunc_ln774_reg_915 and icmp);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(bckgndYUV_empty_n, icmp_ln774_reg_911)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln774_reg_911 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(ovrlayYUV_full_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (ovrlayYUV_full_n = ap_const_logic_0);
    end process;


    ap_condition_227_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_227 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_350_assign_proc : process(icmp_ln774_fu_436_p2, color_read_reg_786, patternId_val_load_read_reg_833, or_ln1963_fu_577_p2)
    begin
                ap_condition_350 <= (not((color_read_reg_786 = ap_const_lv8_1)) and not((color_read_reg_786 = ap_const_lv8_0)) and (icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (or_ln1963_fu_577_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_2));
    end process;


    ap_condition_354_assign_proc : process(icmp_ln774_fu_436_p2, color_read_reg_786, patternId_val_load_read_reg_833, or_ln1963_fu_577_p2)
    begin
                ap_condition_354 <= ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (or_ln1963_fu_577_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_2) and (color_read_reg_786 = ap_const_lv8_1));
    end process;


    ap_condition_372_assign_proc : process(icmp_ln774_fu_436_p2, color_read_reg_786, patternId_val_load_read_reg_833, or_ln1963_fu_577_p2)
    begin
                ap_condition_372 <= ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (or_ln1963_fu_577_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_2) and (color_read_reg_786 = ap_const_lv8_0));
    end process;


    ap_condition_419_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_fu_436_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_833, icmp_ln1884_fu_456_p2)
    begin
                ap_condition_419 <= ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_833 = ap_const_lv8_1));
    end process;


    ap_condition_689_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln774_fu_436_p2, patternId_val_load_read_reg_833, icmp_ln1884_fu_456_p2)
    begin
                ap_condition_689 <= ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln774_fu_436_p2)
    begin
        if (((icmp_ln774_fu_436_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_empty_86_phi_fu_322_p8_assign_proc : process(icmp_ln774_fu_436_p2, patternId_val_load_read_reg_833, icmp_ln1884_fu_456_p2, vDir_load_load_fu_488_p1, icmp_ln1901_fu_492_p2, icmp_ln1906_fu_503_p2, ap_phi_reg_pp0_iter1_empty_86_reg_319)
    begin
        if ((((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1906_fu_503_p2 = ap_const_lv1_0) and (vDir_load_load_fu_488_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)) or ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1901_fu_492_p2 = ap_const_lv1_1) and (vDir_load_load_fu_488_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_86_phi_fu_322_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1901_fu_492_p2 = ap_const_lv1_0) and (vDir_load_load_fu_488_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)) or ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1906_fu_503_p2 = ap_const_lv1_1) and (vDir_load_load_fu_488_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_86_phi_fu_322_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_86_phi_fu_322_p8 <= ap_phi_reg_pp0_iter1_empty_86_reg_319;
        end if; 
    end process;


    ap_phi_mux_empty_87_phi_fu_305_p8_assign_proc : process(icmp_ln774_fu_436_p2, patternId_val_load_read_reg_833, icmp_ln1884_fu_456_p2, hDir_load_load_fu_462_p1, icmp_ln1889_fu_466_p2, icmp_ln1894_fu_477_p2, ap_phi_reg_pp0_iter1_empty_87_reg_302)
    begin
        if ((((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1894_fu_477_p2 = ap_const_lv1_0) and (hDir_load_load_fu_462_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)) or ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1889_fu_466_p2 = ap_const_lv1_1) and (hDir_load_load_fu_462_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_87_phi_fu_305_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1889_fu_466_p2 = ap_const_lv1_0) and (hDir_load_load_fu_462_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)) or ((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (icmp_ln1894_fu_477_p2 = ap_const_lv1_1) and (hDir_load_load_fu_462_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_833 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_87_phi_fu_305_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_87_phi_fu_305_p8 <= ap_phi_reg_pp0_iter1_empty_87_reg_302;
        end if; 
    end process;


    ap_phi_mux_pix_3_phi_fu_368_p12_assign_proc : process(whiYuv_2_q0, color_read_reg_786, patternId_val_load_read_reg_833, icmp_ln774_reg_911_pp0_iter2_reg, or_ln1963_reg_948_pp0_iter2_reg, ap_phi_reg_pp0_iter3_pix_3_reg_364)
    begin
        if ((not((color_read_reg_786 = ap_const_lv8_0)) and (or_ln1963_reg_948_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln774_reg_911_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_833 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_3_phi_fu_368_p12 <= whiYuv_2_q0;
        else 
            ap_phi_mux_pix_3_phi_fu_368_p12 <= ap_phi_reg_pp0_iter3_pix_3_reg_364;
        end if; 
    end process;


    ap_phi_mux_pix_4_phi_fu_350_p12_assign_proc : process(conv2_i_i_i129, color_read_reg_786, patternId_val_load_read_reg_833, icmp_ln774_reg_911_pp0_iter2_reg, or_ln1963_reg_948_pp0_iter2_reg, ap_phi_reg_pp0_iter3_pix_4_reg_347)
    begin
        if ((not((color_read_reg_786 = ap_const_lv8_0)) and (or_ln1963_reg_948_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln774_reg_911_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_833 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_4_phi_fu_350_p12 <= conv2_i_i_i129;
        else 
            ap_phi_mux_pix_4_phi_fu_350_p12 <= ap_phi_reg_pp0_iter3_pix_4_reg_347;
        end if; 
    end process;


    ap_phi_mux_pix_phi_fu_388_p12_assign_proc : process(color_read_reg_786, patternId_val_load_read_reg_833, icmp_ln774_reg_911_pp0_iter2_reg, or_ln1963_reg_948_pp0_iter2_reg, ap_phi_reg_pp0_iter3_pix_reg_384)
    begin
        if ((not((color_read_reg_786 = ap_const_lv8_0)) and (or_ln1963_reg_948_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln774_reg_911_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_833 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_phi_fu_388_p12 <= ap_const_lv8_F0;
        else 
            ap_phi_mux_pix_phi_fu_388_p12 <= ap_phi_reg_pp0_iter3_pix_reg_384;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_phi_ln1975_reg_336 <= "XX";
    ap_phi_reg_pp0_iter0_pix_3_reg_364 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_4_reg_347 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_reg_384 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter1_empty_86_reg_319 <= "X";
    ap_phi_reg_pp0_iter1_empty_87_reg_302 <= "X";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    bckgndYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln774_reg_911, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_blk_n <= bckgndYUV_empty_n;
        else 
            bckgndYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bckgndYUV_read <= bckgndYUV_read_local;

    bckgndYUV_read_local_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln774_reg_911, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_read_local <= ap_const_logic_1;
        else 
            bckgndYUV_read_local <= ap_const_logic_0;
        end if; 
    end process;

    boxBottom_fu_630_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxVCoord_loc_1_fu_136));
    boxHCoord <= 
        sub_ln1914_fu_514_p2 when (ap_phi_mux_empty_87_phi_fu_305_p8(0) = '1') else 
        add_ln1912_fu_519_p2;

    boxHCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_fu_436_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_833, icmp_ln1884_fu_456_p2)
    begin
        if (((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_833 = ap_const_lv8_1))) then 
            boxHCoord_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxHCoord_loc_1_out <= boxHCoord_loc_1_load_reg_906;

    boxHCoord_loc_1_out_ap_vld_assign_proc : process(icmp_ln774_reg_911, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_1) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxRight_fu_625_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxHCoord_loc_1_fu_140));
    boxVCoord <= 
        sub_ln1918_fu_538_p2 when (ap_phi_mux_empty_86_phi_fu_322_p8(0) = '1') else 
        add_ln1916_fu_543_p2;

    boxVCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_fu_436_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_833, icmp_ln1884_fu_456_p2)
    begin
        if (((icmp_ln774_fu_436_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1884_fu_456_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_833 = ap_const_lv8_1))) then 
            boxVCoord_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxVCoord_loc_1_out <= boxVCoord_loc_1_load_reg_901;

    boxVCoord_loc_1_out_ap_vld_assign_proc : process(icmp_ln774_reg_911, ap_block_pp0_stage0_11001, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_911 = ap_const_lv1_1) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    color_read_reg_786 <= color;
    empty_fu_735_p3 <= 
        ap_phi_mux_pix_3_phi_fu_368_p12 when (tobool(0) = '1') else 
        select_ln1991_fu_728_p3;
    hDir_load_load_fu_462_p1 <= hDir;
    icmp_ln1884_fu_456_p2 <= "1" when (or_ln1884_fu_451_p2 = ap_const_lv16_0) else "0";
    icmp_ln1889_fu_466_p2 <= "1" when (unsigned(boxHCoord_loc_1_fu_140) > unsigned(hMax)) else "0";
    icmp_ln1894_fu_477_p2 <= "1" when (unsigned(zext_ln1889_cast_reg_881) > unsigned(boxHCoord_loc_1_fu_140)) else "0";
    icmp_ln1901_fu_492_p2 <= "1" when (unsigned(boxVCoord_loc_1_fu_136) > unsigned(vMax)) else "0";
    icmp_ln1906_fu_503_p2 <= "1" when (unsigned(zext_ln1889_cast_reg_881) > unsigned(boxVCoord_loc_1_fu_136)) else "0";
    icmp_ln1932_1_fu_646_p2 <= "1" when (unsigned(y) < unsigned(boxBottom_fu_630_p2)) else "0";
    icmp_ln1932_fu_635_p2 <= "1" when (unsigned(y) < unsigned(boxVCoord_loc_1_fu_136)) else "0";
    icmp_ln1937_1_fu_662_p2 <= "1" when (unsigned(x_1_reg_895) < unsigned(boxRight_fu_625_p2)) else "0";
    icmp_ln1937_fu_651_p2 <= "1" when (unsigned(x_1_reg_895) < unsigned(boxHCoord_loc_1_fu_140)) else "0";
    icmp_ln1963_fu_572_p2 <= "1" when (x_fu_132 = crossHairX) else "0";
    icmp_ln774_fu_436_p2 <= "1" when (x_fu_132 = loopWidth) else "0";
    motionSpeed_cast_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(motionSpeed),16));
    or_ln1884_fu_451_p2 <= (y or x_fu_132);
    or_ln1963_fu_577_p2 <= (icmp_ln1963_fu_572_p2 or cmp2_i);
    or_ln808_3_fu_742_p4 <= ((p_0_2_0_0_0269598_fu_714_p3 & empty_fu_735_p3) & pixOut_10_fu_721_p3);

    ovrlayYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, ovrlayYUV_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_full_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ovrlayYUV_din <= or_ln808_3_fu_742_p4;
    ovrlayYUV_write <= ovrlayYUV_write_local;

    ovrlayYUV_write_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_write_local <= ap_const_logic_1;
        else 
            ovrlayYUV_write_local <= ap_const_logic_0;
        end if; 
    end process;

    p_0_2_0_0_0269598_fu_714_p3 <= 
        ap_phi_mux_pix_4_phi_fu_350_p12 when (tobool(0) = '1') else 
        select_ln1993_fu_707_p3;
    patternId_val_load_read_reg_833 <= patternId_val_load;
    pixIn_fu_595_p1 <= bckgndYUV_dout(8 - 1 downto 0);
    pixOut_10_fu_721_p3 <= 
        ap_phi_mux_pix_phi_fu_388_p12 when (tobool(0) = '1') else 
        pixOut_9_fu_700_p3;
    pixOut_5_fu_689_p3 <= 
        boxColorB when (and_ln1947_fu_685_p2(0) = '1') else 
        boxColorG;
    pixOut_9_fu_700_p3 <= 
        ap_const_lv8_0 when (and4_i(0) = '1') else 
        ap_phi_mux_pix_phi_fu_388_p12;
    select_ln1911_fu_524_p3 <= 
        sub_ln1914_fu_514_p2 when (ap_phi_mux_empty_87_phi_fu_305_p8(0) = '1') else 
        add_ln1912_fu_519_p2;
    select_ln1915_fu_548_p3 <= 
        sub_ln1918_fu_538_p2 when (ap_phi_mux_empty_86_phi_fu_322_p8(0) = '1') else 
        add_ln1916_fu_543_p2;
    select_ln1975_fu_582_p3 <= 
        ap_const_lv2_2 when (trunc_ln774_fu_447_p1(0) = '1') else 
        ap_const_lv2_1;
    select_ln1991_fu_728_p3 <= 
        ap_const_lv8_0 when (and10_i(0) = '1') else 
        ap_phi_mux_pix_3_phi_fu_368_p12;
    select_ln1993_fu_707_p3 <= 
        ap_const_lv8_0 when (and26_i(0) = '1') else 
        ap_phi_mux_pix_4_phi_fu_350_p12;
    sub_ln1914_fu_514_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_fu_140) - unsigned(motionSpeed_cast_reg_887));
    sub_ln1918_fu_538_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_fu_136) - unsigned(motionSpeed_cast_reg_887));
    trunc_ln774_fu_447_p1 <= x_fu_132(1 - 1 downto 0);
    vDir_load_load_fu_488_p1 <= vDir;
    whiYuv_2_address0 <= zext_ln1975_fu_695_p1(2 - 1 downto 0);

    whiYuv_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            whiYuv_2_ce0_local <= ap_const_logic_1;
        else 
            whiYuv_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    x_2_fu_441_p2 <= std_logic_vector(unsigned(x_fu_132) + unsigned(ap_const_lv16_1));
    xor_ln1932_fu_640_p2 <= (icmp_ln1932_fu_635_p2 xor ap_const_lv1_1);
    xor_ln1937_fu_656_p2 <= (icmp_ln1937_fu_651_p2 xor ap_const_lv1_1);
    zext_ln1889_cast_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1889),16));
    zext_ln1975_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter2_phi_ln1975_reg_336),64));
end behav;
