-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    height_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val : IN STD_LOGIC_VECTOR (15 downto 0);
    patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    dpDynamicRange_val : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef_val : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    height_val4_c3_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    height_val4_c3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c3_full_n : IN STD_LOGIC;
    height_val4_c3_write : OUT STD_LOGIC;
    width_val7_c4_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    width_val7_c4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val7_c4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val7_c4_full_n : IN STD_LOGIC;
    width_val7_c4_write : OUT STD_LOGIC;
    motionSpeed_val14_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val14_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val14_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val14_c_full_n : IN STD_LOGIC;
    motionSpeed_val14_c_write : OUT STD_LOGIC;
    colorFormat_val17_c5_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val17_c5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val17_c5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val17_c5_full_n : IN STD_LOGIC;
    colorFormat_val17_c5_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_4C : STD_LOGIC_VECTOR (7 downto 0) := "01001100";
    constant ap_const_lv8_95 : STD_LOGIC_VECTOR (7 downto 0) := "10010101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_6B : STD_LOGIC_VECTOR (7 downto 0) := "01101011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal height_val4_c3_blk_n : STD_LOGIC;
    signal width_val7_c4_blk_n : STD_LOGIC;
    signal motionSpeed_val14_c_blk_n : STD_LOGIC;
    signal colorFormat_val17_c5_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal cmp2_i_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i10_i236_fu_669_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i10_i236_reg_1313 : STD_LOGIC_VECTOR (7 downto 0);
    signal not_cmp2_i_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_cmp2_i_reg_1318 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i10_i239_fu_683_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i10_i239_reg_1323 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i240_cast_cast_fu_691_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i_i240_cast_cast_reg_1328 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i10_i254_cast_cast_cast_cast_reg_1333 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i_i255_fu_707_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i255_reg_1338 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i268_fu_715_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i268_reg_1343 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i282_fu_723_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i282_reg_1348 : STD_LOGIC_VECTOR (7 downto 0);
    signal barWidth_reg_1353 : STD_LOGIC_VECTOR (10 downto 0);
    signal barWidthMinSamples_fu_771_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_reg_1359 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1364 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_i_i_i_fu_821_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_reg_1369 : STD_LOGIC_VECTOR (10 downto 0);
    signal rampStart_load_reg_1374 : STD_LOGIC_VECTOR (7 downto 0);
    signal cond_i235_fu_831_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal cond_i235_reg_1380 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_94_fu_843_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_94_reg_1385 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_i_fu_847_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_i_reg_1390 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub35_i_fu_855_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub35_i_reg_1395 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub10_i_fu_861_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub10_i_reg_1400 : STD_LOGIC_VECTOR (16 downto 0);
    signal cmp54_i_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp54_i_reg_1405 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp121_i_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp121_i_reg_1410 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp136_i_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp136_i_reg_1415 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_3_reg_1420 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp12_i_fu_1041_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1428 : STD_LOGIC_VECTOR (0 downto 0);
    signal Sel_reg_1433 : STD_LOGIC_VECTOR (1 downto 0);
    signal cmp_i34_fu_1063_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i34_reg_1438 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp11_i_fu_1070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp11_i_reg_1443 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_i349_fu_1076_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_i349_reg_1448 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_452_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_448 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_464_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_460 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_476_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_472 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln563_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rampVal_3_new_0_fu_334 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_330 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal_loc_0_fu_326 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal hBarSel_4_0_loc_0_fu_322 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr_loc_0_fu_318 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_loc_0_fu_314 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_0_loc_0_fu_310 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hdata_new_0_fu_306 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_302 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2_loc_0_fu_298 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0_loc_0_fu_294 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_2_new_0_fu_290 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_286 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_3_loc_0_fu_282 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_5_0_loc_0_fu_278 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal outpix_0_2_0_0_0_load217_lcssa226_fu_270 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_1_0_0_0_load215_lcssa223_fu_266 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_0_0_0_0_load213_lcssa220_fu_262 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln750_fu_1087_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_274 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln563_fu_1031_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln563_fu_953_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1775_fu_945_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1664_fu_933_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1545_fu_917_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1412_fu_909_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1257_fu_893_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal colorFormat_val17_c5_write_local : STD_LOGIC;
    signal motionSpeed_val14_c_write_local : STD_LOGIC;
    signal width_val7_c4_write_local : STD_LOGIC;
    signal height_val4_c3_write_local : STD_LOGIC;
    signal empty_fu_735_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_i_fu_739_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add2_i_fu_755_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_cast_fu_761_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_93_fu_781_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_791_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add5_i_fu_785_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_1_fu_807_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal barHeight_cast_fu_817_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal width_val_cast14_fu_731_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal height_val_cast15_fu_777_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln563_1_fu_1037_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_95_fu_1048_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        width_val : IN STD_LOGIC_VECTOR (15 downto 0);
        conv2_i_i_i282 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i268 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i255 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i240_cast_cast : IN STD_LOGIC_VECTOR (4 downto 0);
        conv2_i_i_i_cast : IN STD_LOGIC_VECTOR (0 downto 0);
        cond_i235 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i254_cast_cast_cast_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        conv2_i_i10_i239 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i236 : IN STD_LOGIC_VECTOR (7 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
        conv2_i_i10_i233_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
        empty : IN STD_LOGIC_VECTOR (7 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        shl_i : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        sub_i_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidthMinSamples : IN STD_LOGIC_VECTOR (9 downto 0);
        cmp11_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp_i34 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub35_i : IN STD_LOGIC_VECTOR (16 downto 0);
        add_i349 : IN STD_LOGIC_VECTOR (7 downto 0);
        icmp : IN STD_LOGIC_VECTOR (0 downto 0);
        Sel_cast : IN STD_LOGIC_VECTOR (1 downto 0);
        cmp54_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp136_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp121_i : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_2_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_2_0_0_0_load216_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_2_0_0_0_load216_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_2_0_0_0_load216_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_1_0_0_0_load214_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_1_0_0_0_load214_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_1_0_0_0_load214_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_0_0_0_0_load212_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_0_0_0_0_load212_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_0_0_0_0_load212_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (7 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        hBarSel_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_0_ap_vld : OUT STD_LOGIC;
        vBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        vBarSel_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_3_0_ap_vld : OUT STD_LOGIC;
        vBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_5_0_ap_vld : OUT STD_LOGIC;
        vBarSel_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        vBarSel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484 : component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_ready,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_din,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_448,
        hdata_flag_0 => hdata_flag_0_reg_460,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_472,
        width_val => width_val,
        conv2_i_i_i282 => conv2_i_i_i282_reg_1348,
        conv2_i_i_i268 => conv2_i_i_i268_reg_1343,
        conv2_i_i_i255 => conv2_i_i_i255_reg_1338,
        conv2_i_i_i240_cast_cast => conv2_i_i_i240_cast_cast_reg_1328,
        conv2_i_i_i_cast => not_cmp2_i_reg_1318,
        cond_i235 => cond_i235_reg_1380,
        conv2_i_i10_i254_cast_cast_cast_cast => conv2_i_i10_i254_cast_cast_cast_cast_reg_1333,
        conv2_i_i10_i239 => conv2_i_i10_i239_reg_1323,
        conv2_i_i10_i236 => conv2_i_i10_i236_reg_1313,
        rampStart_1 => rampStart_load_reg_1374,
        ZplateHorContStart_val => ZplateHorContStart_val,
        patternId_val => patternId_val,
        cmp2_i => cmp2_i_reg_1308,
        conv2_i_i10_i233_cast => rampStart_load_reg_1374,
        y => y_3_reg_1420,
        colorFormat_val => colorFormat_val,
        empty => empty_94_reg_1385,
        barWidth_cast => barWidth_reg_1353,
        barWidth => barWidth_reg_1353,
        shl_i => shl_i_reg_1390,
        ZplateHorContDelta_val => ZplateHorContDelta_val,
        ZplateVerContStart_val => ZplateVerContStart_val,
        cmp12_i => cmp12_i_reg_1428,
        ZplateVerContDelta_val => ZplateVerContDelta_val,
        sub_i_i_i => sub_i_i_i_reg_1369,
        barWidthMinSamples => barWidthMinSamples_reg_1359,
        cmp11_i => cmp11_i_reg_1443,
        cmp_i34 => cmp_i34_reg_1438,
        sub35_i => sub35_i_reg_1395,
        add_i349 => add_i349_reg_1448,
        icmp => icmp_reg_1364,
        Sel_cast => Sel_reg_1433,
        cmp54_i => cmp54_i_reg_1405,
        cmp136_i => cmp136_i_reg_1415,
        cmp121_i => cmp121_i_reg_1410,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_330,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_326,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_0_loc_1_out_i => hBarSel_4_0_loc_0_fu_322,
        hBarSel_4_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o,
        hBarSel_4_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_318,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o_ap_vld,
        vBarSel_loc_1_out_i => vBarSel_loc_0_fu_314,
        vBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o,
        vBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o_ap_vld,
        hBarSel_0_loc_1_out_i => hBarSel_0_loc_0_fu_310,
        hBarSel_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o,
        hBarSel_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_302,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o_ap_vld,
        vBarSel_2_loc_1_out_i => vBarSel_2_loc_0_fu_298,
        vBarSel_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o,
        vBarSel_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o_ap_vld,
        hBarSel_3_0_loc_1_out_i => hBarSel_3_0_loc_0_fu_294,
        hBarSel_3_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o,
        hBarSel_3_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_286,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o_ap_vld,
        vBarSel_3_loc_1_out_i => vBarSel_3_loc_0_fu_282,
        vBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o,
        vBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o_ap_vld,
        hBarSel_5_0_loc_1_out_i => hBarSel_5_0_loc_0_fu_278,
        hBarSel_5_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o,
        hBarSel_5_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o_ap_vld,
        outpix_0_2_0_0_0_load216_out_i => outpix_0_2_0_0_0_load217_lcssa226_fu_270,
        outpix_0_2_0_0_0_load216_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o,
        outpix_0_2_0_0_0_load216_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o_ap_vld,
        outpix_0_1_0_0_0_load214_out_i => outpix_0_1_0_0_0_load215_lcssa223_fu_266,
        outpix_0_1_0_0_0_load214_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o,
        outpix_0_1_0_0_0_load214_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o_ap_vld,
        outpix_0_0_0_0_0_load212_out_i => outpix_0_0_0_0_0_load213_lcssa220_fu_262,
        outpix_0_0_0_0_0_load212_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o,
        outpix_0_0_0_0_0_load212_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_ap_vld,
        hBarSel_4_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0,
        hBarSel_4_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_ap_vld,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_ap_vld,
        hBarSel_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0,
        hBarSel_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_ap_vld,
        vBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel,
        vBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_ap_vld,
        hBarSel_3_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0,
        hBarSel_3_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_ap_vld,
        vBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2,
        vBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_ap_vld,
        hBarSel_5_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0,
        hBarSel_5_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_ap_vld,
        vBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1,
        vBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_0_loc_0_fu_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_0_loc_0_fu_310 <= zext_ln1545_fu_917_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_0_loc_0_fu_310 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_3_0_loc_0_fu_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_3_0_loc_0_fu_294 <= zext_ln1664_fu_933_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_3_0_loc_0_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_4_0_loc_0_fu_322_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_4_0_loc_0_fu_322 <= hBarSel_4_0;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_4_0_loc_0_fu_322 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_5_0_loc_0_fu_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_5_0_loc_0_fu_278 <= zext_ln563_fu_953_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_5_0_loc_0_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_460_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                hdata_flag_0_reg_460 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_flag_1_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hdata_flag_0_reg_460 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hdata_loc_0_fu_302 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hdata_loc_0_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_472_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                rampVal_2_flag_0_reg_472 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_flag_1_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_2_flag_0_reg_472 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_2_loc_0_fu_286 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_2_loc_0_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_448_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                rampVal_3_flag_0_reg_448 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_flag_1_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_3_flag_0_reg_448 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_330_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_3_loc_0_fu_330 <= rampVal_1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_3_loc_0_fu_330 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_326_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_loc_0_fu_326 <= zext_ln1257_fu_893_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_loc_0_fu_326 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_2_loc_0_fu_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                vBarSel_2_loc_0_fu_298 <= vBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                vBarSel_2_loc_0_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_3_loc_0_fu_282_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                vBarSel_3_loc_0_fu_282 <= zext_ln1775_fu_945_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                vBarSel_3_loc_0_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_loc_0_fu_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                vBarSel_loc_0_fu_314 <= zext_ln1412_fu_909_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                vBarSel_loc_0_fu_314 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_274_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                y_fu_274 <= ap_const_lv16_0;
            elsif (((icmp_ln563_fu_1026_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_274 <= add_ln563_fu_1031_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                zonePlateVAddr_loc_0_fu_318 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                zonePlateVAddr_loc_0_fu_318 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                Sel_reg_1433 <= y_fu_274(7 downto 6);
                add_i349_reg_1448 <= add_i349_fu_1076_p2;
                cmp11_i_reg_1443 <= cmp11_i_fu_1070_p2;
                cmp12_i_reg_1428 <= cmp12_i_fu_1041_p2;
                cmp_i34_reg_1438 <= cmp_i34_fu_1063_p2;
                y_3_reg_1420 <= y_fu_274;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                barWidthMinSamples_reg_1359 <= barWidthMinSamples_fu_771_p2;
                barWidth_reg_1353 <= add_i_fu_739_p2(13 downto 3);
                cmp121_i_reg_1410 <= cmp121_i_fu_873_p2;
                cmp136_i_reg_1415 <= cmp136_i_fu_879_p2;
                cmp2_i_reg_1308 <= cmp2_i_fu_663_p2;
                cmp54_i_reg_1405 <= cmp54_i_fu_867_p2;
                cond_i235_reg_1380 <= cond_i235_fu_831_p3;
                    conv2_i_i10_i236_reg_1313(1 downto 0) <= conv2_i_i10_i236_fu_669_p3(1 downto 0);    conv2_i_i10_i236_reg_1313(5 downto 4) <= conv2_i_i10_i236_fu_669_p3(5 downto 4);    conv2_i_i10_i236_reg_1313(7) <= conv2_i_i10_i236_fu_669_p3(7);
                    conv2_i_i10_i239_reg_1323(0) <= conv2_i_i10_i239_fu_683_p3(0);    conv2_i_i10_i239_reg_1323(2) <= conv2_i_i10_i239_fu_683_p3(2);    conv2_i_i10_i239_reg_1323(4) <= conv2_i_i10_i239_fu_683_p3(4);    conv2_i_i10_i239_reg_1323(7) <= conv2_i_i10_i239_fu_683_p3(7);
                    conv2_i_i10_i254_cast_cast_cast_cast_reg_1333(0) <= conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3(0);    conv2_i_i10_i254_cast_cast_cast_cast_reg_1333(2) <= conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3(2);
                    conv2_i_i_i240_cast_cast_reg_1328(0) <= conv2_i_i_i240_cast_cast_fu_691_p3(0);    conv2_i_i_i240_cast_cast_reg_1328(2) <= conv2_i_i_i240_cast_cast_fu_691_p3(2);    conv2_i_i_i240_cast_cast_reg_1328(4) <= conv2_i_i_i240_cast_cast_fu_691_p3(4);
                    conv2_i_i_i255_reg_1338(2) <= conv2_i_i_i255_fu_707_p3(2);    conv2_i_i_i255_reg_1338(4) <= conv2_i_i_i255_fu_707_p3(4);    conv2_i_i_i255_reg_1338(7) <= conv2_i_i_i255_fu_707_p3(7);
                    conv2_i_i_i268_reg_1343(7) <= conv2_i_i_i268_fu_715_p3(7);
                    conv2_i_i_i282_reg_1348(6 downto 0) <= conv2_i_i_i282_fu_723_p3(6 downto 0);
                empty_94_reg_1385 <= empty_94_fu_843_p1;
                icmp_reg_1364 <= icmp_fu_801_p2;
                not_cmp2_i_reg_1318 <= not_cmp2_i_fu_677_p2;
                rampStart_load_reg_1374 <= rampStart;
                    shl_i_reg_1390(15 downto 8) <= shl_i_fu_847_p3(15 downto 8);
                sub10_i_reg_1400 <= sub10_i_fu_861_p2;
                sub35_i_reg_1395 <= sub35_i_fu_855_p2;
                sub_i_i_i_reg_1369 <= sub_i_i_i_fu_821_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_3_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hBarSel_5_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_phi_mux_hdata_flag_0_phi_fu_464_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                hdata <= hdata_new_0_fu_306;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hdata_new_0_fu_306 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                outpix_0_0_0_0_0_load213_lcssa220_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_0_0_0_0_load212_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                outpix_0_1_0_0_0_load215_lcssa223_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_1_0_0_0_load214_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                outpix_0_2_0_0_0_load217_lcssa226_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_outpix_0_2_0_0_0_load216_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampStart <= add_ln750_fu_1087_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_3_flag_0_phi_fu_452_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_1 <= rampVal_3_new_0_fu_334;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_2_flag_0_phi_fu_476_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_2 <= rampVal_2_new_0_fu_290;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal_2_new_0_fu_290 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal_3_new_0_fu_334 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_vBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_zonePlateVAddr;
            end if;
        end if;
    end process;
    conv2_i_i10_i236_reg_1313(3 downto 2) <= "11";
    conv2_i_i10_i236_reg_1313(6) <= '1';
    conv2_i_i10_i239_reg_1323(1) <= '0';
    conv2_i_i10_i239_reg_1323(3 downto 3) <= "0";
    conv2_i_i10_i239_reg_1323(6 downto 5) <= "00";
    conv2_i_i_i240_cast_cast_reg_1328(1) <= '0';
    conv2_i_i_i240_cast_cast_reg_1328(3) <= '0';
    conv2_i_i10_i254_cast_cast_cast_cast_reg_1333(1) <= '0';
    conv2_i_i_i255_reg_1338(1 downto 0) <= "11";
    conv2_i_i_i255_reg_1338(3 downto 3) <= "1";
    conv2_i_i_i255_reg_1338(6 downto 5) <= "11";
    conv2_i_i_i268_reg_1343(6 downto 0) <= "0000000";
    conv2_i_i_i282_reg_1348(7) <= '1';
    shl_i_reg_1390(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done, icmp_ln563_fu_1026_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add2_i_fu_755_p2 <= std_logic_vector(unsigned(empty_fu_735_p1) + unsigned(ap_const_lv14_F));
    add5_i_fu_785_p2 <= std_logic_vector(unsigned(empty_93_fu_781_p1) + unsigned(ap_const_lv14_F));
    add_i349_fu_1076_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(empty_95_fu_1048_p1));
    add_i_fu_739_p2 <= std_logic_vector(unsigned(empty_fu_735_p1) + unsigned(ap_const_lv14_7));
    add_ln563_fu_1031_p2 <= std_logic_vector(unsigned(y_fu_274) + unsigned(ap_const_lv16_1));
    add_ln750_fu_1087_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(motionSpeed_val));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val4_c3_full_n, width_val7_c4_full_n, motionSpeed_val14_c_full_n, colorFormat_val17_c5_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (colorFormat_val17_c5_full_n = ap_const_logic_0) or (motionSpeed_val14_c_full_n = ap_const_logic_0) or (width_val7_c4_full_n = ap_const_logic_0) or (height_val4_c3_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln563_fu_1026_p2)
    begin
        if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_464_p4 <= hdata_flag_0_reg_460;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_476_p4 <= rampVal_2_flag_0_reg_472;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_452_p4 <= rampVal_3_flag_0_reg_448;

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln563_fu_1026_p2)
    begin
        if (((icmp_ln563_fu_1026_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    barHeight_cast_fu_817_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_807_p4),11));
    barWidthMinSamples_fu_771_p2 <= std_logic_vector(unsigned(p_cast_fu_761_p4) + unsigned(ap_const_lv10_3FF));
    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_din;

    bckgndYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_bckgndYUV_write;
        else 
            bckgndYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp11_i_fu_1070_p2 <= "1" when (sub10_i_reg_1400 = zext_ln563_1_fu_1037_p1) else "0";
    cmp121_i_fu_873_p2 <= "1" when (dpYUVCoef_val = ap_const_lv8_0) else "0";
    cmp12_i_fu_1041_p2 <= "0" when (y_fu_274 = ap_const_lv16_0) else "1";
    cmp136_i_fu_879_p2 <= "0" when (colorFormat_val = ap_const_lv8_1) else "1";
    cmp2_i_fu_663_p2 <= "1" when (colorFormat_val = ap_const_lv8_0) else "0";
    cmp54_i_fu_867_p2 <= "1" when (dpDynamicRange_val = ap_const_lv8_0) else "0";
    cmp_i34_fu_1063_p2 <= "1" when (y_fu_274 = ap_const_lv16_0) else "0";

    colorFormat_val17_c5_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, colorFormat_val17_c5_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val17_c5_blk_n <= colorFormat_val17_c5_full_n;
        else 
            colorFormat_val17_c5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    colorFormat_val17_c5_din <= colorFormat_val;
    colorFormat_val17_c5_write <= colorFormat_val17_c5_write_local;

    colorFormat_val17_c5_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            colorFormat_val17_c5_write_local <= ap_const_logic_1;
        else 
            colorFormat_val17_c5_write_local <= ap_const_logic_0;
        end if; 
    end process;

    cond_i235_fu_831_p3 <= 
        rampStart when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv8_80;
    conv2_i_i10_i236_fu_669_p3 <= 
        ap_const_lv8_FF when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv8_4C;
    conv2_i_i10_i239_fu_683_p3 <= 
        ap_const_lv8_0 when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv8_95;
    conv2_i_i10_i254_cast_cast_cast_cast_fu_699_p3 <= 
        ap_const_lv3_0 when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv3_5;
    conv2_i_i_i240_cast_cast_fu_691_p3 <= 
        ap_const_lv5_0 when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv5_15;
    conv2_i_i_i255_fu_707_p3 <= 
        ap_const_lv8_FF when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv8_6B;
    conv2_i_i_i268_fu_715_p3 <= 
        ap_const_lv8_0 when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv8_80;
    conv2_i_i_i282_fu_723_p3 <= 
        ap_const_lv8_FF when (cmp2_i_fu_663_p2(0) = '1') else 
        ap_const_lv8_80;
    empty_93_fu_781_p1 <= height_val(14 - 1 downto 0);
    empty_94_fu_843_p1 <= s(8 - 1 downto 0);
    empty_95_fu_1048_p1 <= y_fu_274(8 - 1 downto 0);
    empty_fu_735_p1 <= width_val(14 - 1 downto 0);
    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_484_ap_start_reg;

    height_val4_c3_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val4_c3_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_c3_blk_n <= height_val4_c3_full_n;
        else 
            height_val4_c3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val4_c3_din <= height_val;
    height_val4_c3_write <= height_val4_c3_write_local;

    height_val4_c3_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            height_val4_c3_write_local <= ap_const_logic_1;
        else 
            height_val4_c3_write_local <= ap_const_logic_0;
        end if; 
    end process;

    height_val_cast15_fu_777_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_val),17));
    icmp_fu_801_p2 <= "0" when (tmp_fu_791_p4 = ap_const_lv7_0) else "1";
    icmp_ln563_fu_1026_p2 <= "1" when (y_fu_274 = height_val) else "0";

    motionSpeed_val14_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, motionSpeed_val14_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val14_c_blk_n <= motionSpeed_val14_c_full_n;
        else 
            motionSpeed_val14_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    motionSpeed_val14_c_din <= motionSpeed_val;
    motionSpeed_val14_c_write <= motionSpeed_val14_c_write_local;

    motionSpeed_val14_c_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            motionSpeed_val14_c_write_local <= ap_const_logic_1;
        else 
            motionSpeed_val14_c_write_local <= ap_const_logic_0;
        end if; 
    end process;

    not_cmp2_i_fu_677_p2 <= (cmp2_i_fu_663_p2 xor ap_const_lv1_1);
    p_cast_fu_761_p4 <= add2_i_fu_755_p2(13 downto 4);
    shl_i_fu_847_p3 <= (rampStart & ap_const_lv8_0);
    sub10_i_fu_861_p2 <= std_logic_vector(unsigned(height_val_cast15_fu_777_p1) + unsigned(ap_const_lv17_1FFFF));
    sub35_i_fu_855_p2 <= std_logic_vector(unsigned(width_val_cast14_fu_731_p1) + unsigned(ap_const_lv17_1FFFF));
    sub_i_i_i_fu_821_p2 <= std_logic_vector(unsigned(barHeight_cast_fu_817_p1) + unsigned(ap_const_lv11_7FF));
    tmp_1_fu_807_p4 <= add5_i_fu_785_p2(13 downto 4);
    tmp_fu_791_p4 <= colorFormat_val(7 downto 1);

    width_val7_c4_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val7_c4_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val7_c4_blk_n <= width_val7_c4_full_n;
        else 
            width_val7_c4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val7_c4_din <= width_val;
    width_val7_c4_write <= width_val7_c4_write_local;

    width_val7_c4_write_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            width_val7_c4_write_local <= ap_const_logic_1;
        else 
            width_val7_c4_write_local <= ap_const_logic_0;
        end if; 
    end process;

    width_val_cast14_fu_731_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_val),17));
    zext_ln1257_fu_893_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
    zext_ln1412_fu_909_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel),8));
    zext_ln1545_fu_917_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_0),8));
    zext_ln1664_fu_933_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_3_0),8));
    zext_ln1775_fu_945_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel_1),8));
    zext_ln563_1_fu_1037_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_274),17));
    zext_ln563_fu_953_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_5_0),8));
end behav;
